### ISSUE TITLE
Filling polygons near to Greenwich

### ISSUE THREAD

**Issue by nicgar20** [EL-BID/BabelGrid#11]
So I have been trying to get quadkeys for countries like Spain or France, but I am getting an error, after it I tried to fill a small box near greenwich and I still get this error

Polygon examples that get this error
```
poly = Polygon([[0.01, 20], [0.2, 20], [0.2, 20.5], [0.01, 20.5], [0.01, 20]])
poly = Polygon([[-0.1, 20], [0.1, 20], [0.1, 20.5], [-0.1, 20.5], [-0.1, 20]])
```

after executing:
```
tiles = Babel("bing").polyfill(poly, resolution=18)
```
 I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/babelgrid.py", line 322, in polyfill
    for tile_id in quadtree.polyfill(geometry.shapely, resolution)
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/quadtree.py", line 66, in polyfill
    return _get_contained_keys(geometry, _get_initial_tile(geometry), resolution)
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/quadtree.py", line 59, in _get_contained_keys
    func(initial_key, False)
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/quadtree.py", line 46, in func
    area_ratio = _area_ratio(_key_to_shapely(key), geometry)
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/quadtree.py", line 11, in _key_to_shapely
    return wkt.loads(tile_to_geo_boundary(key))
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/babelgrid/quadtree.py", line 71, in tile_to_geo_boundary
    a = Tile.from_quad_tree(key)
  File "/home/nicgar/software/anaconda3/envs/obmgap/lib/python3.9/site-packages/pygeotile/tile.py", line 21, in from_quad_tree
    google_x, google_y = [reduce(lambda result, bit: (result << 1) | bit, bits, 0)
```

It seems like there is an issue in pygeotile, can it be fixed from Babelgrid?

**Comment by JoaoCarabetta** [comment]
Hi @nicgar20, I will take a look on this. The `bing` grid was not behaving well.

**Comment by JoaoCarabetta** [comment]
I managed to get good results with both polygons (see image below).  I am also using python3.9. 

Do you have the actual error? You just printed the traceback.

![image](https://user-images.githubusercontent.com/19963732/128030028-d4aebf3e-edad-4e90-a711-d65e70b75453.png)

**Comment by nicgar20** [comment]
Sorry, the error I get is: 
```
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by JoaoCarabetta** [comment]
Is it working for different regions?

**Comment by nicgar20** [comment]
Yes, it works fine elsewhere
